import type { VideoJob, Project, Segment } from '@/lib/types'
import { createWhisperService } from '@/lib/whisper'

interface JobProcessorDependencies {
  updateJobStatus: (jobId: string, updates: Partial<VideoJob>) => void
  setProjects: React.Dispatch<React.SetStateAction<Project[]>>
}

export class VideoJobProcessor {
  private whisperService = createWhisperService()
  
  constructor(private deps: JobProcessorDependencies) {}

  async processJob(job: VideoJob): Promise<void> {
    throw new Error('Use processJobWithFile instead')
  }
  
  async processJobWithFile(job: VideoJob, videoFile: File): Promise<void> {
    console.log('🎬 Starting job processor for:', job.id, job.fileName)
    
    try {
      // Step 1: Transcription phase
      console.log('🎙️ Starting transcription phase')
      this.deps.updateJobStatus(job.id, { 
        status: 'transcribing'
      })
      
      const transcript = await this.generateTranscript(videoFile)
      console.log('✅ Transcription completed, length:', transcript.length)
      
      // Step 2: Analysis phase
      console.log('🧠 Starting analysis phase') 
      this.deps.updateJobStatus(job.id, { 
        status: 'analyzing'
      })
      
      const { duration, segments } = await this.analyzeVideo(videoFile, transcript)
      console.log('✅ Analysis completed, segments:', segments.length)
      
      // Step 3: Complete job
      console.log('🎯 Completing job')
      this.deps.updateJobStatus(job.id, {
        status: 'completed',
        duration: duration,
        segmentCount: segments.length
      })
      
      // Step 4: Create project
      const project = await this.createProject(job, videoFile, transcript, segments, duration)
      this.deps.setProjects(currentProjects => {
        const existingProjects = Array.isArray(currentProjects) ? currentProjects : []
        return [project, ...existingProjects]
      })
      
      console.log('🎉 Job processing completed successfully:', job.id)
      
    } catch (error) {
      console.error('❌ Job processing failed:', error)
      throw error // Re-throw to be handled by queue
    }
  }
  
  private async generateTranscript(videoFile: File): Promise<string> {
    try {
      const result = await this.whisperService.transcribeVideo(videoFile)
      return result.text || ''
    } catch (error) {
      console.error('Transcription failed:', error)
      // Return mock transcript as fallback
      return this.getMockTranscript(videoFile)
    }
  }
  
  private getMockTranscript(videoFile: File): string {
    return `This is a mock transcription for ${videoFile.name}. In a real scenario, this would be generated by Whisper or another speech-to-text service.`
  }
  
  private async analyzeVideo(videoFile: File, transcript: string): Promise<{ duration: number; segments: Segment[] }> {
    // Simulate video analysis delay
    await new Promise(resolve => setTimeout(resolve, 2000))
    
    // Get video duration
    const duration = await this.getVideoDuration(videoFile)
    
    // Generate segments based on transcript and duration
    const segments = this.generateSegments(duration, transcript)
    
    return { duration, segments }
  }
  
  private async getVideoDuration(videoFile: File): Promise<number> {
    return new Promise((resolve) => {
      const video = document.createElement('video')
      video.preload = 'metadata'
      
      video.onloadedmetadata = () => {
        window.URL.revokeObjectURL(video.src)
        resolve(Math.floor(video.duration))
      }
      
      video.onerror = () => {
        console.warn('Could not get video duration, using default')
        resolve(120) // Default 2 minutes
      }
      
      video.src = URL.createObjectURL(videoFile)
    })
  }
  
  private generateSegments(duration: number, transcript: string): Segment[] {
    const segmentCount = 6
    const segmentDuration = duration / segmentCount
    
    const titles = [
      'Introduction',
      'Timeline Interface', 
      'Cutting Techniques',
      'Transitions',
      'Audio Mixing',
      'Conclusion'
    ]
    
    const descriptions = [
      'Welcome and overview of the tutorial',
      'Understanding the timeline and clip arrangement',
      'Different methods for cutting video clips',
      'Adding smooth transitions between clips', 
      'Balancing audio levels and adding music',
      'Recap and final thoughts'
    ]
    
    return titles.map((title, index) => ({
      id: `seg-${index + 1}`,
      title,
      startTime: Math.floor(index * segmentDuration),
      endTime: index === segmentCount - 1 ? duration : Math.floor((index + 1) * segmentDuration),
      description: descriptions[index]
    }))
  }
  
  private async createProject(
    job: VideoJob, 
    videoFile: File, 
    transcript: string, 
    segments: Segment[], 
    duration: number
  ): Promise<Project> {
    const videoUrl = URL.createObjectURL(videoFile)
    
    return {
      id: `project-${Date.now()}`,
      name: job.fileName,
      jobId: job.id,
      videoUrl,
      duration,
      transcript,
      segments
    }
  }
}